In [1]:
import os
import numpy as np

from Stationary.core import *

from sklearn import linear_model

In [2]:
w1 = Worker(mean = np.array([0, 0]), model=linear_model.LinearRegression())
w2 = Worker(mean = np.array([0, 0]),  model=linear_model.LinearRegression())
w3 = Worker(mean = np.array([0, 0]),  model=linear_model.LinearRegression())

In [3]:
l = []
l.append(w1)
l.append(w2)
l.append(w3)

In [4]:
server = Server(mean = np.array([0, 0]), workers = l, num_features = 2)

In [5]:
'''
for i in l:
    i.train(X = np.array([[0,0], [1,1], [2,2]]), y = np.array([[1],[2],[3]]))
    
'''

'\nfor i in l:\n    i.train(X = np.array([[0,0], [1,1], [2,2]]), y = np.array([[1],[2],[3]]))\n    \n'

In [6]:
w1.train(X = np.array([[0,0], [1,1], [2,2]]), y = np.array([[1],[2],[3]]))
w2.train(X = np.array([[0,2], [1,5], [3,2]]), y = np.array([[1],[3],[4]]))
w3.train(X = np.array([[0,3], [1,2], [1,2]]), y = np.array([[1],[5],[1]]))

array([[ 1., -1.]])

In [7]:
w3.model.coef_

array([[ 1., -1.]])

In [8]:
server.aggregation()

[[0.5 0.5]]
[[1.         0.33333333]]
[[ 1. -1.]]


In [9]:
server.mean

array([[ 0.83333333, -0.05555556]])

In [10]:
server.return_to_workers()

In [11]:
w3.mean

array([[ 0.83333333, -0.05555556]])